twig:
  file_name_pattern: '*.twig'
  paths:
    # point this wherever your images live
    '%kernel.project_dir%/public/assets/images': images
    '%kernel.project_dir%/assets/styles': styles

when@test:
    twig:
        strict_variables: true
